spring.application.name=POS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123sebass
spring.datasource.generate-unique-name=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# JWT Configuration
jwt.secret=3mJrM7pKxQvN2wL9dF4sH6yB8aG5jT1uC0nP2qR3vW4xZ5yA6bE7cF8dG9hI0jK
